#!/bin/bash
# every time change something, please save it!


type=an200epi

stimall=${stim_dir}whisker_123.txt
procstimall=${date}.${mouse_num}.stimall
afni_proc.py -subj_id ${procstimall}                 \
-dsets reg.${filen}*.${type}_regtotemp+orig.HEAD \
-copy_anat reg.${filen}flash+orig          \
-anat_has_skull no                              \
-blocks despike volreg mask blur scale regress        \
-volreg_base_dset reg.${filen}flash+orig        \
-volreg_post_vr_allin yes                       \
-volreg_pvra_base_index MIN_OUTLIER             \
-mask_epi_anat no                               \
-blur_size 0.3                                  \
-mask_import 100mask ${template_dir}100maskAMBMC+orig	\
-mask_apply 100mask	
-regress_stim_times ${stimall}                 \
-regress_apply_mask				\
-regress_stim_labels vis                        \
-regress_basis 'BLOCK(4,1)'                     \
-regress_censor_motion 0.5                      \
-regress_censor_outliers 0.02                   \
-regress_apply_mot_types demean deriv           \
-regress_motion_per_run                         \
-regress_run_clustsim no                        \
-regress_compute_fitts                          \
-regress_make_ideal_sum sum_ideal.1D            \
-regress_est_blur_epits                         \
-regress_est_blur_errts                                                                 

tcsh -xef proc.${procstimall} |& tee output.proc.${procstimall}


rm ${procstimall}.results/pb0*
rm ${procstimall}.results/errts*
rm ${procstimall}.results/fitts*

