#!/bin/bash
# copy the folder to your place
# change the dirs in n_mysetting
# change the setting in n_command
# save 
# run the n_command with "sh n_command"


savefile=/local_mount/space/yulab/3/users/hike_processed/average_random/
script_dir=/local_mount/space/yulab/3/users/hike_processed/script/runbyonce/
#preprocessing for correlation
proname=restforave_8s


setting=("04122023" "N1" "13" "12 11 10")
# date mouse_Num T1_num EPI_num
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
#source ${script_dir}D_o_procforcorr_regtotemp
###source ${script_dir}temp_corr_rest
cd ${filen}${mouse_num}.${proname}.results/
3dcalc -a censor_${filen}${mouse_num}.${proname}_combined_2.1D -b errts.${filen}${mouse_num}.${proname}.tproject+orig -expr '(a*b)' -prefix ${savefile}${filen}${mouse_num}.ave_data

cp censor_${filen}${mouse_num}.${proname}_combined_2.1D ${savefile}${filen}${mouse_num}.ave_motout.1D

cd ${savefile}
3dcopy ${filen}${mouse_num}.ave_data formean_data
cp ${filen}${mouse_num}.ave_motout.1D formean_motout.1D


setting=("04122023" "N2" "29" "26 27 28")
# date mouse_Num T1_num EPI_num
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
#source ${script_dir}D_o_procforcorr_regtotemp
###source ${script_dir}temp_corr_rest
cd ${filen}${mouse_num}.${proname}.results/
3dcalc -a censor_${filen}${mouse_num}.${proname}_combined_2.1D -b errts.${filen}${mouse_num}.${proname}.tproject+orig -expr '(a*b)' -prefix ${savefile}${filen}${mouse_num}.ave_data

cp censor_${filen}${mouse_num}.${proname}_combined_2.1D ${savefile}${filen}${mouse_num}.ave_motout.1D

cd ${savefile}
3dcopy formean_data t_formean_data
cp formean_motout.1D t_formean_motout.1D

rm formean_data+orig.*
rm formean_motout.1D
3dcalc -a ${filen}${mouse_num}.ave_data+orig -b t_formean_data+orig -expr 'a+b' -prefix formean_data
1deval -a ${filen}${mouse_num}.ave_motout.1D -b t_formean_motout.1D -expr 'a+b' > formean_motout.1D



setting=("04132023" "N1" "27" "24 25 26")
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
source ${script_dir}r_beforeave_random

setting=("04132023" "N2" "38" "37 36 35")
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
source ${script_dir}r_beforeave_random

setting=("04202023" "N2" "19" "16 18 17")
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
source ${script_dir}r_beforeave_random

setting=("04212023" "N2" "26" "24 23 25")
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
source ${script_dir}r_beforeave_random

setting=("04272023" "N1" "26" "23 24 25")
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
source ${script_dir}r_beforeave_random

setting=("04282023" "N2" "13" "10 11 9")
# date mouse_Num T1_num EPI_num
source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}temp_corr_rest
source ${script_dir}r_beforeave_random

#if there some dataset missing, using these scripts
#setting=("04272023" "N1" "26" "23 24 25") #the order of EPI num must be #1 #2 #3 
## date mouse_Num T1_num EPI_num
#source ${script_dir}D_n_mysetting_reg
#source ${script_dir}o_procforcorr_regtoChose
#source ${script_dir}D_o_corr_stimall_random
#source ${script_dir}temp_corr_rest
#source ${script_dir}r_beforeave


cd ${savefile}

3dcalc -a formean_data+orig -b formean_motout.1D -expr 'a/b' -prefix allMice.average

source ${script_dir}n_command_averagedcorr_random



#correlation for stimulation
#setting=("07292022" "9" "16" "13 14 15")
# date mouse_Num T1_num EPI_num

#source ${script_dir}D_o_corr_stim 
#source ${script_dir}D_o_corr_stimall
#source ${script_dir}o_corr_stimall_tent &
#source ${script_dir}o_corr_AM2reg

#correlation for resting state
#setting=("09122022" "AD02" "23" "21 22 28")
# date mouse_Num T1_num EPI_num
#source ${script_dir}n_mysetting
#source ${script_dir}o_corr_rest








